/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventana;


import Modelos.CategoriaListaDoble;
import Modelos.UsuarioLista;
import Paneles.Biblioteca;
import Paneles.Convertidor;
import Paneles.Login;
import java.awt.BorderLayout;

/**
 *
 * @author Gerardo
 */
public class ventana extends javax.swing.JFrame {

    /**
     * Creates new form ventana
     */
    Login log = new Login();
    UsuarioLista usuarioL = new UsuarioLista(); 
    CategoriaListaDoble catL = new CategoriaListaDoble();
  
   
  
    

    public ventana() {
        initComponents();
        this.setTitle("Biblioteca");
        cambiarPanel(log);
        log.ListaUser(usuarioL);
        log.listaFotos(catL);
       
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Salirpanel = new javax.swing.JPanel();
        salir = new javax.swing.JButton();
        panelBase = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1107, 586));

        Salirpanel.setBackground(new java.awt.Color(102, 0, 102));

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SalirpanelLayout = new javax.swing.GroupLayout(Salirpanel);
        Salirpanel.setLayout(SalirpanelLayout);
        SalirpanelLayout.setHorizontalGroup(
            SalirpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SalirpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(salir)
                .addGap(37, 37, 37))
        );
        SalirpanelLayout.setVerticalGroup(
            SalirpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SalirpanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(salir)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelBaseLayout = new javax.swing.GroupLayout(panelBase);
        panelBase.setLayout(panelBaseLayout);
        panelBaseLayout.setHorizontalGroup(
            panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1065, Short.MAX_VALUE)
        );
        panelBaseLayout.setVerticalGroup(
            panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 645, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(Salirpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Salirpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        log = new Login();    
        log.ListaUser(usuarioL);
        log.listaFotos(catL);
        cambiarPanel(log);
        
       
        System.out.println("Funciono el cambio");
           
           
          
           
    }//GEN-LAST:event_salirActionPerformed

    /**
     * @param args the command line arguments
     */
   
    private void cambiarPanel(javax.swing.JPanel miPanel){
        miPanel.setSize(1065, 645);
        miPanel.setLocation(0,0);
        panelBase.removeAll();
        panelBase.add(miPanel, BorderLayout.CENTER);
        panelBase.revalidate();
        panelBase.repaint(); 
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Salirpanel;
    private javax.swing.JPanel panelBase;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
