/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paneles;

import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import proyecto2.JPEGHandler;
import proyecto2.JPEGImageCopy;
import proyecto2.JPEGImageHandlerBN;
import proyecto2.JPEGImageHandlerColors;
import proyecto2.JPEGImageHandlerRotator;
import proyecto2.JPEGtoBMPImage;

/**
 *
 * @author Gerardo
 */
public class Convertidor extends javax.swing.JPanel {

    /**
     * Creates new form Convertidor
     */
    public Convertidor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagen = new javax.swing.JLabel();
        Jpg_a_bpm = new javax.swing.JRadioButton();
        subir = new javax.swing.JButton();
        copia = new javax.swing.JRadioButton();
        colores = new javax.swing.JRadioButton();
        modificar = new javax.swing.JRadioButton();
        ByN = new javax.swing.JRadioButton();

        imagen.setText("Imagen");

        Jpg_a_bpm.setText("JPEG A BMMP Y VICEVERSA");

        subir.setText("Seleccionar Imagen");
        subir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subirActionPerformed(evt);
            }
        });

        copia.setText("Copia JPEG");
        copia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copiaActionPerformed(evt);
            }
        });

        colores.setText("ROJO VERDE AZUL SERPIA");

        modificar.setText("MODIFICAR IMAGEN");

        ByN.setText("Blanco y negro");
        ByN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ByNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 367, Short.MAX_VALUE)
                .addComponent(subir)
                .addGap(116, 116, 116))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(copia)
                            .addComponent(Jpg_a_bpm)
                            .addComponent(colores)
                            .addComponent(modificar)
                            .addComponent(ByN)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(imagen)
                .addGap(1, 1, 1)
                .addComponent(subir)
                .addGap(16, 16, 16)
                .addComponent(Jpg_a_bpm)
                .addGap(18, 18, 18)
                .addComponent(copia)
                .addGap(18, 18, 18)
                .addComponent(colores)
                .addGap(18, 18, 18)
                .addComponent(modificar)
                .addGap(18, 18, 18)
                .addComponent(ByN)
                .addContainerGap(116, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void subirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subirActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Seleccione una imagen");
        chooser.setFileFilter(new FileNameExtensionFilter("Archivos de imagen","jpg","bmp"));

        int resultado = chooser.showOpenDialog(this);
        
        if(Jpg_a_bpm.isSelected()){
            if(resultado == JFileChooser.APPROVE_OPTION) {
                File selectedFile = chooser.getSelectedFile();
                ImageIcon imageIcon = new ImageIcon(selectedFile.getAbsolutePath());
                 JPEGtoBMPImage handlerJPG = new JPEGtoBMPImage(imageIcon.toString().replace("\\", "/")); 
                imagen.setText(imageIcon.toString());
            try{
                JPEGHandler.runHandler(handlerJPG);
            }catch(Exception e){
                e.printStackTrace();
            }
           }
        }if(copia.isSelected()){
            if(resultado == JFileChooser.APPROVE_OPTION) {
                System.out.println("Llego");
                    File selectedFile = chooser.getSelectedFile();
                    ImageIcon imageIcon = new ImageIcon(selectedFile.getAbsolutePath());
                     JPEGImageCopy handlerCopy = new JPEGImageCopy(imageIcon.toString().replace("\\", "/")); 
                    imagen.setText(imageIcon.toString());
                try{
                    JPEGHandler.runHandler(handlerCopy);
                }catch(Exception e){
                    e.printStackTrace();
                }
            }
        }if(colores.isSelected()){
        if(resultado == JFileChooser.APPROVE_OPTION) {
                System.out.println("Llego");
                    File selectedFile = chooser.getSelectedFile();
                    ImageIcon imageIcon = new ImageIcon(selectedFile.getAbsolutePath());
                     JPEGImageHandlerColors handlerColors = new JPEGImageHandlerColors(imageIcon.toString().replace("\\", "/")); 
                    imagen.setText(imageIcon.toString());
                try{
                    JPEGHandler.runHandler(handlerColors);
                }catch(Exception e){
                    e.printStackTrace();
                }
            }
        }if(modificar.isSelected()){
            if(resultado == JFileChooser.APPROVE_OPTION) {
                File selectedFile = chooser.getSelectedFile();
                String fileName = selectedFile.getName(); 
                ImageIcon imageIcon = new ImageIcon(selectedFile.getAbsolutePath());
                 JPEGImageHandlerRotator handlerRotatio = new JPEGImageHandlerRotator(imageIcon.toString().replace("\\", "/")); 
                imagen.setText(imageIcon.toString());
            try{
                JPEGHandler.runHandler(handlerRotatio);
            }catch(Exception e){
                e.printStackTrace();
            }
           
            }
        }if(ByN.isSelected()){
            if(resultado == JFileChooser.APPROVE_OPTION) {
                File selectedFile = chooser.getSelectedFile();
                String fileName = selectedFile.getName(); 
                ImageIcon imageIcon = new ImageIcon(selectedFile.getAbsolutePath());
                 JPEGImageHandlerBN handlerBn = new JPEGImageHandlerBN(imageIcon.toString().replace("\\", "/")); 
                imagen.setText(imageIcon.toString());
            try{
                JPEGHandler.runHandler(handlerBn);
            }catch(Exception e){
                e.printStackTrace();
            }
           
            }
            }
       
    }//GEN-LAST:event_subirActionPerformed
       
    private void ByNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ByNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ByNActionPerformed

    private void copiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_copiaActionPerformed
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ByN;
    private javax.swing.JRadioButton Jpg_a_bpm;
    private javax.swing.JRadioButton colores;
    private javax.swing.JRadioButton copia;
    private javax.swing.JLabel imagen;
    private javax.swing.JRadioButton modificar;
    private javax.swing.JButton subir;
    // End of variables declaration//GEN-END:variables
}
